import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function SSR({ title }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>{process.env.SSR_TITLE}</h1>
    </div>
  );
}

export const getServerSideProps = async () => {
  return {
    props: {
      title: `${Math.random() * 1000}`,
    },
  };
};
